### ISSUE TITLE
Manage falco config and rules dependency

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/evolution#10]
**Motivation**

The Falco configuration and rules files are now statically copied from the current Falco's master version.

**Feature**

A smarter dependency management solution is needed.

**Alternatives**

A non-smart but rapid solution could be to point out the user to the available versions of Falco's default configuration and rules files.

**Additional context**

As for [this PR](https://github.com/falcosecurity/contrib/pull/9) the configuration and rules files are copied only as a temporary solution to the [first PR](https://github.com/falcosecurity/contrib/pull/3) since the integrations were initially intended to be part of the Falco project (and repo).

**Comment by leogr** [comment]
/reopen

This is still an issue, IMHO.
