### ISSUE TITLE
Create a new repo for Falco cpp plugin sdk: plugin-sdk-cpp

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/evolution#121]
**Description of Request**

**It will just be a move** from the current place (ie: inside the https://github.com/falcosecurity/plugins repo) to a new place: `plugin-sdk-cpp`.

**Motivation**
It does not feel ok to leave the sdk inside the repo that will host Falco plugins provided by falcosecurity.  
Therefore, we follow same approach that was taken with https://github.com/falcosecurity/plugin-sdk-go. 

Thanks!

**Comment by leogr** [comment]
Good idea. 

@FedeDP Would you like to create the new repo? If yes, once done ping me and I help you to transfer it from your account to the falcosecurity org. Then we will finish the setup.

/assign

**Comment by FedeDP** [comment]
Of course! I will ping back once it is created.

**Comment by FedeDP** [comment]
The repo has been created using falcosecurity/template-repository: https://github.com/FedeDP/plugin-sdk-cpp

**Comment by leogr** [comment]
> The repo has been created using falcosecurity/template-repository: https://github.com/FedeDP/plugin-sdk-cpp

Great! Just a small issue: could you align the OWNERS file with the one in the [plugin repo](https://github.com/falcosecurity/plugins/blob/master/OWNERS)?
