### ISSUE TITLE
Donate falco-aws-terraform module to falcosecurity

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/evolution#132]
**Description of Request**

I'd like to add a terrraform module that creates necessary aws cloud resources to connect AWS Cloudtrail with the cloudtrail falco plugin.

The module is at https://github.com/mstemm/falco-cloudtrail-terraform. It was copied almost verbatim from the sysdig terraform module for the [cloud-connector](https://github.com/sysdiglabs/terraform-aws-secure-for-cloud), with their permission. That terraform module does a lot more, like deploying sysdig applications in addition to aws resources. I kept just the parts that are used for the `single-account` example, which should cover the most common use cases.

Once donated, we can ask users to try it out and then iterate and/or bring over additional features from the sysdig module.

**Motivation**

The cloudtrail plugin is very powerful, but it requires a fair amount of setup to create the cloudtrail, s3 buckets, sns topic, sqs queue, etc. This automates this process and reduces the friction for users who want to use the cloudtrail plugin.

**Comment by leogr** [comment]
Nice!

+1 for me :)

**Comment by mstemm** [comment]
I removed some temporary files that were added by mistake, and also renamed the primary branch from "master" to "main".

**Comment by jasondellaluce** [comment]
This is cool! 🎉

**Comment by mstemm** [comment]
When I import the repository to the falcosecurity org, I'm going to use the name `falco-aws-terraform`, as the terraform module creates various aws resources and not just cloudtrail resources. I renamed the upstream repo to falco-aws-terraform and updated the name in this issue to match.

**Comment by mstemm** [comment]
Ok, repository is moved: https://github.com/falcosecurity/falco-aws-terraform. And the test-infra PR to get it managed via poiana/prow is https://github.com/falcosecurity/test-infra/pull/668.

**Comment by mstemm** [comment]
We'll have to make some tweaks to the test-infra PR, but the repo is moved, so closing this issue.
