### ISSUE TITLE
Donate probe-builder/kernel_crawler to falcosecurity

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/evolution#133]
**Description of Request**

I'd like the [kernel_crawler](https://github.com/draios/probe-builder/tree/dev/probe_builder/kernel_crawler) from the draios/probe-builder repo to be donated to falcosecurity.
It will be used as a github action to maintain a list of currently available kernels in various distros; the output json will be then parsed by clients (namely, test-infra) to automatically generate driverkit configs.

Note: i'd like to donate my own fork instead: https://github.com/FedeDP/kernel-crawler, as it already provides arm64 support + has already github actions in place.

Possibly, i'd name the new repo `kernel_crawler` instead of probe-builder because it will just contain the kernel_crawler part.

**Motivation**

Lack of prebuilt drivers is nowadays possibly the main adoption friction for Falco. We need a kernel crawler to be able to auto-generate configs for driverkit; draios already has one, so use it!

**Comment by maxgio92** [comment]
As discussed, this is an important step forward I think. Thanks @FedeDP 🤗 

I working on a kernel releases crawler, but as of now is a WIP.

**Comment by leogr** [comment]
+1 for me

Question: who is willing to maintain the project?

**Comment by FedeDP** [comment]
I think i can; @maxgio92 too i guess :)

**Comment by zuc** [comment]
I'm also volunteering!

**Comment by maxgio92** [comment]
Me too @leogr @FedeDP :)

**Comment by FedeDP** [comment]
And here it is: https://github.com/falcosecurity/kernel-crawler :)
