### ISSUE TITLE
Donate libs-sdk to falcosecurity

### ISSUE THREAD

**Issue by araujof** [falcosecurity/evolution#135]
**Description of Request**

We would like to donate our experimental [Libs SDK](https://github.com/sysflow-telemetry/libs-sdk) to falcosecurity.

**Motivation**

We think that this project will be a catalyst for the adoption of Falco Libs by the community. The Libs SDK simplifies the creation of Libs consumers for different programming languages and provides a recipe for building compact Libs consumer images. Currently, the SDK defines a C API and a Golang wrapper for the Libs, and contains examples of how to build Libs consumers in C, C++, and Go. It can be expanded to support other languages in the future.

As discussed in our community call (4/20/22), a Libs SDK would enhance the Libs ecosystem and enable several use cases. E.g., 
- Simplification and documentation of a build process for Libs consumers (without requiring expert knowledge of the Libs)
- Rapid prototyping of Libs tools for testing new ideas, concepts, automating tasks, etc. 
- Creation of analytics tools for scap in various languages 
- Creation of new layers of data abstraction on top of the scap format (e.g., SysFlow)
- Enable integrations with data science and analytics frameworks
- A playground for the community and Libs contributors to establish and evolve the Libs ecosystem and APIs.

**Comment by jasondellaluce** [comment]
I think this is fantastic and I'm onboard for this being part of the Falcosecurity org! Looking forward to hear what other maintainers think, and hopefully we'll get this repo donated soon! 😄

**Comment by Andreagit97** [comment]
Thank you @araujof for this huge work :heart_eyes:! I think that this SDK can simplify a lot the creation of Libs consumers also for people who don't have expert knowledge of the Libs, and this is amazing! I can't wait to see it into Falcosecurity :rocket::clap::clap:

**Comment by Andreagit97** [comment]
> +1 for me
> 
> I also volunteer to be a maintainer of this incubating project. Does anybody else mind joining?

If you want I can help you in doing this :+1:

**Comment by leogr** [comment]
I'm moving the repo today and starting configuring it! :partying_face:

**Comment by jasondellaluce** [comment]
I think this is addressed now! What do you all think?

**Comment by maxgio92** [comment]
I think this can be closed @jasondellaluce me too. Do you agree @leogr @araujof?

**Comment by leogr** [comment]
We just miss a PR to update the [projects list](https://github.com/falcosecurity/evolution#projects). @araujof Would you mind making it?

**Comment by leogr** [comment]
It's all set.

/close
