### ISSUE TITLE
Puppet module docs and release needed

### ISSUE THREAD

**Issue by genebean** [falcosecurity/evolution#142]
**Describe the bug**

As noted in https://github.com/falcosecurity/falco/issues/2005, the module at https://forge.puppet.com/modules/sysdig/falco does not point to this repository. It also seems that this repo has had enhancements merged since the last release to the Puppet Forge.

**How to reproduce it**

View https://forge.puppet.com/modules/sysdig/falco

**Expected behaviour**

I expect the docs in the published Puppet module to reference the current home of the repo.

**Comment by genebean** [comment]
Closing as I have rewored this code into a standalone module. The current module cannot be installed via git because it is not in the root of a repo / a repo by itself. I will open a new issue requesting the new module be referenced instead.

**Comment by maxgio92** [comment]
Ok, thanks for the update @genebean
