### ISSUE TITLE
Promote de-facto official projects

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#144]
**Description of Request**

The following projects (or part of them) are de-facto officially supported: 

- [Falco Helm Chart](https://github.com/falcosecurity/charts/tree/master/falco)
- [Falco K8S manifest files](https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/falco), which are autogenerated from the Helm Chart
- [Plugin registry](https://github.com/falcosecurity/plugins) and those hosted plugins [bundled in the official Falco package](https://github.com/falcosecurity/falco/blob/master/cmake/modules/plugins.cmake) (a notable example is the [k8saudit](https://github.com/falcosecurity/plugins/tree/master/plugins/k8saudit) plugin that replaced a Falco core feature)
- [plugin-go-sdk](https://github.com/falcosecurity/plugin-sdk-go) which is the foundation of officially distributed plugins

However, those projects are currently documented as incubating projects. This request aims to regularize their statuses by promoting them to "Official support".

**Motivation**

By this time, those projects are a fundamental part of the Falco release process and are partially documented on the official website. Some of them provide artifacts distributed along with the Falco official release. Since users recognize them as part of the Falco ecosystem, maintainers regularly keep them up-to-date during the release cycle. Thus, promoting them to "Official Support" is mostly a formality but also a way to document the support level users should expect.

**The plan**

To satisfy this request, we have to perform just a few small steps (mostly documentation). Here is the list:

-  [x] Promote https://github.com/falcosecurity/charts to "Official support"
       _Each chart inherits its status from the related project (the Falco chart will be official, falcosidekick and falco-exporter charts will remain incubating)_
-  [x] Create a repository for [K8s manifest files](https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes) and promote it to "Official support"
       _Each manifest set inherits its status from the related project_
- [x] Promote https://github.com/falcosecurity/plugins to "Official support" 
        _The status of each single plugin (or logical group of them)_
- [x] Promote https://github.com/falcosecurity/plugin-sdk-go to "Official support"

NB
In practice, promoting a project just means updating its status within [this table](https://github.com/falcosecurity/evolution#projects).

**Comment by maxgio92** [comment]
I agree for all of them, according to the [adoption model](https://github.com/falcosecurity/evolution#adoption-model).

I don't have visibility of the usage of [bare manifests](https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/falco), BTW they are generated from the de-facto official [helm chart](https://github.com/falcosecurity/charts/tree/master/falco), so IMHO they also inherit the adoption level.

> As a side note, as discussed with @leogr this latter case needs a further work in otder to migrate the manifests generation CI jobs.

**Comment by leogr** [comment]
> I don't have visibility of the usage of [bare manifests](https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/falco), BTW they are generated from the de-facto official [helm chart](https://github.com/falcosecurity/charts/tree/master/falco), so IMHO they also inherit the adoption level.
> 
> > As a side note, as discussed with @leogr this latter case needs a further work in otder to migrate the manifests generation CI jobs.

Correct. Basically, we have to change the [periodic job](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/update-falco-k8s-manifests/update-falco-k8s-manifests.yaml#L1) to a postsubmit one (so manifests get updated immediately after an Helm chart release). I will fix that!

**Comment by leogr** [comment]
> Big +1 on my side too - I'm also interested in helping with k8s manifests should current maintainers think they need some sort of help

We definitively need help :) 
Would you like to help in maintaining that project?
If yes, +1 for me
