### ISSUE TITLE
Kubernetes Audit Logs

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/evolution#145]
**Motivation**

To Enable K8s Audit Logs in Cloud Environments

**Feature**

How do we enable k8s Audit logs in AWS,Azure and GCP.

**Comment by jasondellaluce** [comment]
Hey @ajinkya1986, in the upcoming Falco 0.32 we are migrating the support to K8S Audit Logs to the new Plugin System: https://github.com/falcosecurity/plugins/tree/master/plugins/k8saudit

Here you can find the current documentation: https://falco.org/docs/event-sources/kubernetes-audit/
This will be updated after the Falco 0.32 release (~June 3rd) with new instructions on how to run the new plugin implementation.

So far, we still only support the K8S Events webhook backend, but we plan to create plugin flavors for some of those cloud providers. From a quick internet search, here's also an example of how this was adapted to AWS EKS: https://faun.pub/analyze-aws-eks-audit-logs-with-falco-95202167f2e#:~:text=Falco%20is%20a%20Kubernetes%20threat,send%20audit%20logs%20to%20CloudWatch.

**Comment by ajinkya1986** [comment]
Thankyou @jasondellaluce  for the quick reply

**Comment by leogr** [comment]
Hey @ajinkya1986 

Has this issue been addressed?

**Comment by ajinkya1986** [comment]
Hi @leogr We have not tested it out yet

**Comment by leogr** [comment]
The plugin has been released https://github.com/falcosecurity/plugins/releases/tag/k8saudit-eks-0.1.0

**Comment by maxgio92** [comment]
Hi @ajinkya1986, did you have a chance to try the plugin since it has been released?
Thank you

**Comment by leogr** [comment]
> Hi @ajinkya1986, did you have a chance to try the plugin since it has been released? Thank you

ping

@ajinkya1986 any updates?
