### ISSUE TITLE
Archive falcosecurity/template-repository

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/evolution#154]
**Describe the bug**

I don't see the value of having a template repository, whose only guarantee is adding a default license and an inaccurate `OWNERS` file.
We normally create repositories, and before donating it to `falcosecurity`, make sure that the OWNERS and the LICENSE files are in place. The README should also be there with an explanation of the projects and a little overview.

Furthermore, most of the projects under this organization do not use it. It has never been used consistently, and it is not maintained anymore.

**Proposal**

Given the above, I propose to archive `falcosecurity/template-repository` repository.

**Comment by maxgio92** [comment]
Is the license the right one for potentially all projects of the organization?

**Comment by maxgio92** [comment]
Besides the content, I think the three files is important they're always in place. So I propose to revive the template repo and instead revisit the content where necessary. My 2 cents :-)

**Comment by leogr** [comment]
Hey @maxgio92 

> Is the license the right one for potentially all projects of the organization?

The license should be Apache2, but others are allowed :point_down: 
https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy

So I don't find it so useful for that purpose.

Moreover, has no sense to me to inherit the `OWNERS` file from the template (and unfortunately we can't remove it from there, otherwise the repo won't work). I still believe keeping it has more cons than pros.

cc @falcosecurity/falco-maintainers wdyt?

**Comment by leogr** [comment]
> +1 as long as we document the owners file expectations in our governance

That's a good point :+1:

**Comment by jasondellaluce** [comment]
+1 from me for archiving the repo.

The template repository has not been used consistently in the past, and I don't think that having default files for license and owners serves any purpose in the organization. Those are both repo-dependent things that should be evaluated case by case. At this point, I feel like having this repository just causes degrees of confusion when contributing new projects to the organization.

> +1 as long as we document the owners file expectations in our governance

Totally agree!

**Comment by leogr** [comment]
> Besides the content, I think the three files is important they're always in place. So I propose to revive the template repo and instead revisit the content where necessary. My 2 cents :-)

Hey @maxgio92 

from the community call feedback and this issue comment, most folks agree on archiving the project. However, I understood you want to revive the repo. At this point, I'd propose to archive the project anyway and eventually unarchive it when we know how to use it and rework it. Meanwhile, users will not be confused by a template repository that has not been consistently used and is currently not up-to-date.

So, could we proceed with archiving it, or do you still have any concerns? Let us know!

**Comment by maxgio92** [comment]
Hi @leogr,
I like the approach and the mine wasn't a strong opinion. Please, go on with the archival :-)
