### ISSUE TITLE
Document OWNERS file usage

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#158]
**What to document**

Maintainership in our repository is automated and relies on the `OWNERS` file spec 
(see https://www.kubernetes.dev/docs/guide/owners/). 

However, we have never explicitly documented it. I'd like to document that in our [governance](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md).

This idea was initially proposed by @kris-nova in [this comment](https://github.com/falcosecurity/evolution/issues/154#issuecomment-1184682181).

**Comment by maxgio92** [comment]
I agree with this and like it @leogr

**Comment by jasondellaluce** [comment]
I agree on this! +1
