### ISSUE TITLE
[training] katacoda repo at falcosecurity

### ISSUE THREAD

**Issue by pabloopez** [falcosecurity/evolution#160]
**Describe the bug**

(Not a bug, but there's not a better category for this issues). We detected that O'Reilly closed down last month the free service that we used to host the labs here: https://github.com/falcosecurity/katacoda-scenarios

Hence, none of this content is available any more. I suggest to archive this repository for now.

**How to reproduce it**

Just visit katacoda.com or any of the labs. 

**Expected behaviour**

**Additional context**

**Comment by jasondellaluce** [comment]
If the content is no more available, I see no point in leaving the repo open! +1 for archiving it, thanks @pabloopez!

**Comment by leogr** [comment]
As discussed during yesterday's community call, there's no way this repository can continue to work since https://www.katacoda.com/ is now closed. Thus, I'm going to archive the repo soon.

Anyway, I want to say thank you to @pabloopez , for the great job he did with Katacoda :clap:
