### ISSUE TITLE
Move "sandbox" code to its own repository

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#170]
**Motivation**

As this repository is becoming more and more critical for decision-making and documenting the whole project, I think it would be a good idea not to mix the documentation with the experimental code. I find it more straightforward and consistent that such source code would live in its repository.

**Feature**

1. create the `falcosecurity/contrib` repository
2. Move the following directories (preserving the git history) to the new repository:
  - https://github.com/falcosecurity/evolution/tree/master/examples
  - https://github.com/falcosecurity/evolution/tree/master/integrations
  - https://github.com/falcosecurity/evolution/tree/master/usage-metrics/distribution-logs (or to test-infra?)
3. Update the [README.md](https://github.com/falcosecurity/evolution#sandbox) accordingly  

**Alternatives**

We might altogether remove the sandbox level. But I'd like that since such experimental code is still important to test-drive ideas or to provide examples.

**Additional context**

`contrib` is the former name of `evolution` and has also been suggested by @maxgio92, so I really believe it's the perfect name :smile_cat:

**Comment by maxgio92** [comment]
As discussed we're on the same page and I like the idea to have a `contrib`-dedicated repository.

**Comment by jasondellaluce** [comment]
I like this idea!

**Comment by leogr** [comment]
I'm working on this

/assign
