### ISSUE TITLE
Switch default branch to `main` (evolution repository)

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#178]
**Motivation**

I'd like to begin an effort to make all the language and terms more inclusive. 
Switching to `main` is just one small step in that direction.

**Feature**

Change the default branch of this repository to `main`

**Alternatives**

**Additional context**

**Comment by maxgio92** [comment]
I agree with that, thanks @leogr

**Comment by leogr** [comment]
In progress

**Comment by leogr** [comment]
Done. I'm doing the same thing also for `.github` and `community`.
