### ISSUE TITLE
broken link from Falco101 training

### ISSUE THREAD

**Issue by caligin** [falcosecurity/evolution#180]
**Describe the bug**

The [Falco 101 training](https://learn.sysdig.com/falco-101/), in section `101.05` - lab #4 "Kubernetes Audit Events" requires downloading an audit policy from this repo using the url `https://raw.githubusercontent.com/falcosecurity/evolution/master/examples/k8s_audit_config/audit-policy.yaml`. this results in a 404 as the content was deletes and moved to a different repo in 9e9af0f1566704b107fa210339dd823ac179fc4a .

**How to reproduce it**

Take the [Falco 101 training](https://learn.sysdig.com/falco-101/) and skip content until section `101.05` - lab #4 "Kubernetes Audit Events". The script for that lab contains the line:
`wget https://raw.githubusercontent.com/falcosecurity/evolution/master/examples/k8s_audit_config/audit-policy.yaml`

**Expected behaviour**

The commands in the training can be copypasted in the lab sandbox environment to completion without tweaking

**Comment by leogr** [comment]
I apologize for this problem :sweat_smile: 

Thank you, @pmusa, for the quick fix.

/close
