### ISSUE TITLE
Document our code review process

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#182]
**What to document**

Our code review process is very similar to [The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process) (because we use the same automation of Kubernetes, i.e. Prow), but not exactly the same.

Some notable differences:

 - In parallel to the Prow workflow, we enforce GitHub review too (so `/approve` is not enough, the maintainer also has to select the _Approved_ checkbox and push the **Submit review** green button on the GitHub UI.
 - For some repositories, we require a double approval (only for the `falco` and `libs` repositories), and we should explain why and when using this strategy
 - A positive GitHub review implies the _approved_ label, so one does not have to write `/approve` explicitly; however, that's not true for all repositories (for example, `test-infra` requires an explicit `/approve`)

Moreover, our beloved @poiana sometimes believes to be the K8s robot and writes potentially misleading messages to the users :smile_cat: 

For example :point_down: https://github.com/falcosecurity/test-infra/pull/824#issuecomment-1233113339
![image](https://user-images.githubusercontent.com/3390997/187869941-ec26f9bc-fe11-4f1d-9765-b011abc2b834.png)

Along with some improvements in our code review process implemented, I think we should write down a `REVIEW_PROCESS.md` to help contributors understand our workflow.

Thanks :grinning:

**Comment by zuc** [comment]
FTR - the way to change the link referenced in the poiana message is this one: https://github.com/kubernetes/test-infra/blob/61a8c725cbd70fec2dc9002bb2aef39837829f78/prow/plugins/config.go#L323

**Comment by h4l0gen** [comment]
Hey @leogr , if this issue is available to work on, I would like to take it on. It sounds exciting! However, I'll need some initial assistance as I haven't created a document file describing processes before, and I'm eager to learn about documentation practices. Additionally, if there are any specific preferences or requirements, please let me know so I can incorporate them effectively.

**Comment by leogr** [comment]
> Hey @leogr , if this issue is available to work on, I would like to take it on. It sounds exciting! However, I'll need some initial assistance as I haven't created a document file describing processes before, and I'm eager to learn about documentation practices. Additionally, if there are any specific preferences or requirements, please let me know so I can incorporate them effectively.

Sure! You can work on this! 

I recommend you become familiar with our review process first. When you feel confident, we will work on the documentation.

**Comment by h4l0gen** [comment]
Thanks, am starting with this [https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process](url) as it is nearly same process as falco have. Is this right way to start?

**Comment by leogr** [comment]
> Thanks, am starting with this [https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process](url) as it is nearly same process as falco have. Is this right way to start?

Yes. I also recommend to observe @poiana (who's our [@k8s-ci-robot](https://github.com/k8s-ci-robot/) in PRs.

**Comment by h4l0gen** [comment]
Hey @leogr, I'm done with the Falco review process and have studied the Prow documentation. If I need to reference any specific steps, I'll conduct additional research. For now, let's begin working on the documentation.

**Comment by leogr** [comment]
> Hey @leogr, I'm done with the Falco review process and have studied the Prow documentation. If I need to reference any specific steps, I'll conduct additional research. For now, let's begin working on the documentation. Please guide me through some initial steps.

Would you like to start a draft?

I believe the steps would be:
- Try to add a new section, "How the Review Process Works" to https://github.com/falcosecurity/.github/blob/main/contributing/review-process.md
- Take inspiration from https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process
- Adapt it according our process (see the notable differences in the description of this issue)

Then I (and I guess also @incertum) will be happy to take a look and give first feedback. 

@h4l0gen Would this work for you?

**Comment by h4l0gen** [comment]
Thanks, @leogr. Yes, it works for me. I will make a draft of this shortly.
