### ISSUE TITLE
Document Adoption Process

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/evolution#19]
**Motivation**

With more and more integrations being baked into the community, can we please

 - Document the process requesting for adoption
 - Document the process of regesting a repository 
 - Add a github issue type each of those to this repo

**Feature**

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
Regarding the 3rd point, I can create custom GitHub template issues that merge/override the default ones we have (at the organization level).

We already did this for the falco-website repo (look [here](https://github.com/falcosecurity/falco-website/tree/master/.github)).

So my proposal is... 👇 

Each template issue will automatically insert one of the following GitHub labels.
Thus we'll have 3 template issue.

adoption/sandbox request -> `kind/adoption` -> matches [contrib/sandbox](https://github.com/falcosecurity/falco/blob/master/proposals/20200506-artifacts-scope-part-1.md#contrib) level: in a sub-directory of this repo
incubation request -> `kind/incubation` -> matches [repository/incubating](https://github.com/falcosecurity/falco/blob/master/proposals/20200506-artifacts-scope-part-1.md#repository) level: obtain a repository in the `falcosecurity` org
offical support request -> `kind/officialsupport` -> matches [official support](https://github.com/falcosecurity/falco/blob/master/proposals/20200506-artifacts-scope-part-1.md#official-support): the tool/artifact/etc. becomes an official support project of Falco (can remain in its own repo or be adopted into the Falco one depending on the nature of the thing).

WDYT?

**Comment by leogr** [comment]
I like the labels! I would just use `kind/sandbox` instead of `kind/adoption` so we will able to use those labels for all issues not just requesting ones.

Btw, If you want to document the process, please add that on top of https://github.com/falcosecurity/contrib/pull/24
There you can found the new README. Thanks
