### ISSUE TITLE
Dockerhub: cleanup old and not used repositories

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#216]
**Motivation**

I've noticed that our [dockerhub account](https://hub.docker.com/u/falcosecurity) contains several legacies and (now) not used any more repositories (e.g. some have not been used in the last 3 years)

**Feature**

Just delete those repositories we are not using anymore.

**Alternatives**

**Additional context**

**Comment by leogr** [comment]
cc @falcosecurity/falco-maintainers @falcosecurity/test-infra-maintainers

**Comment by FedeDP** [comment]
Fully agree to clean them up; :+1: from me

**Comment by leogr** [comment]
Can we prepare a list of which are still active?

@falcosecurity/core-maintainers 
/help
