### ISSUE TITLE
Donate mstemm/flycheck-falco-rules to falcosecurity organization

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/evolution#221]
**Repository**: https://github.com/mstemm/flycheck-falco-rules

**Motivation**

Hi, I'd like to donate an emacs syntax checker for falco rules to the falcosecurity organization. For emacs users, it allows on-the-fly validation of falco rules files with in-editor feedback about errors and warnings as you're editing a file. I think it's a very valuable tool for rule authors to help them get to working rules faster.

There are screenshots, tests, and a fully formed .el file in the github repo.

I'm going to search around for a second maintainer but I wanted to open this evolution issue first so I can point potential maintainers to it.

**Comment by maxgio92** [comment]
Hey @mstemm! That's cool! Thank you very much 🤗 

+1 for me :-) 

What about you @falcosecurity/evolution-maintainers?

**Comment by jasondellaluce** [comment]
+1 for me as well! This is cool!

**Comment by leogr** [comment]
Cool
+1 for me!

cc @falcosecurity/core-maintainers

**Comment by FedeDP** [comment]
Very cool! +1!

**Comment by leogr** [comment]
Hey @mstemm 

I think you can transfer the repo to the org and setup the repo config in test-infra and here.
Let me know if you need any support

**Comment by mstemm** [comment]
Ok, I've imported mstemm/flycheck-falco-rules as falcosecurity/flycheck-falco-rules. https://github.com/falcosecurity/test-infra/pull/994 is the PR for test-infra, https://github.com/falcosecurity/evolution/pull/247 adds it to evolution. Let me know if I missed any locations.
