### ISSUE TITLE
Donate maxgio92/peribolos-syncer

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/evolution#269]
**Repository**:  https://github.com/maxgio92/peribolos-syncer

**Motivation**

There are two declarative sources of truth about people of the GitHub organization:
- [Peribolos](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/) configuration
- OWNERS ([approvers and reviewers](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/))

the first honored by GitHub access control, and the latter by Prow automation's access control (like through the [verify-owner](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/verify-owners)s plugin).

The tool can be used in CI to trigger, after the merge of PRs which bring changes to the owners, synchronization of the Peribolos configuration, via pull request.

**Additional context**

* See [here](https://github.com/falcosecurity/test-infra/pull/1120) a preview of the integration mentioned above.
* See [here](https://github.com/falcosecurity/test-infra/pull/1117) for a demo.

**Comment by leogr** [comment]
I love it!

+1 from me

**Comment by maxgio92** [comment]
cc @falcosecurity/core-maintainers WDYT?

If approved I'm going to propose the repository settings, thanks.

**Comment by cpanato** [comment]
+1

**Comment by maxgio92** [comment]
Thank you all :-)

**Comment by maxgio92** [comment]
If anyone would like to help let me know

**Comment by cpanato** [comment]
> If anyone would like to help let me know

let me know what you need :)

**Comment by maxgio92** [comment]
Thanks @cpanato! Right now the tool is pretty simple and it's doing the work, but maintainers are more than welcome :-)

**Comment by maxgio92** [comment]
Oh, obviously the code and code coverage have space for improvement!

**Comment by FedeDP** [comment]
Very nice and great work! +1 from me!
Thank you Max!

**Comment by Andreagit97** [comment]
great work! +1 from me!

**Comment by leogr** [comment]
Hey @maxgio92 

Are you ready to move it to Falcosecurity?

Let me know if you need any support! I will be happy to help

**Comment by leogr** [comment]
Repo trasfered https://github.com/falcosecurity/peribolos-syncer
We will set up @poiana and the rest soon.

But, we first need maintainers for the project. Who volunteers? :smile_cat: 

Ofc, count me in :)

**Comment by maxgio92** [comment]
I'm going to declare the owners here: https://github.com/falcosecurity/peribolos-syncer/pull/5
It's work in progress, so anyone who wants to join can comment there :-)

**Comment by leogr** [comment]
Hey @maxgio92 

Is this complete?

**Comment by maxgio92** [comment]
Yep @leogr! 🥰
Thanks for noting this. I'm going to close it
