### ISSUE TITLE
Donate alacuku/e2e-falco-tests to falcosecurity

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/evolution#282]
**Repository**:  
https://github.com/alacuku/e2e-falco-tests

**Motivation**

We need a testing framework for the Falco libs and drivers. It should test drivers (`kmod, bpf and modern bpf`) across a wide range of different kernel and distribution. 

This repository is a starting point for such a framework. The solution is based on `ansible playbooks` and `firecracker`. It allows the creation of `micro-vms` which are based on a selected set of `kernels` and `root filesystems` which are packaged as OCI images. The `ansible-playbook` makes it easy to mix and match any kernel and any base image to create a VM. Once the VMs are up and running it transfers precompiled tests and runs them on every machine to make sure that our builds are compatible with a given set of kernels.

The `playbooks` have been developed to be run in local development machines and CI systems.

Example on how the machines are created starting from a given set of kernels and base images: 
```yaml
machines:
  - {name: "5.8.18",kernel: "docker.io/aldokcl/dronet:5.8.18-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.9.16",kernel: "docker.io/aldokcl/dronet:5.9.16-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.10.152",kernel: "docker.io/aldokcl/dronet:5.10.152-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.11.22",kernel: "docker.io/aldokcl/dronet:5.11.22-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.12.19",kernel: "docker.io/aldokcl/dronet:5.12.19-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.13.19",kernel: "docker.io/aldokcl/dronet:5.13.19-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.14.21",kernel: "docker.io/aldokcl/dronet:5.14.21-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.15.76",kernel: "docker.io/aldokcl/dronet:5.15.76-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.16.20",kernel: "docker.io/aldokcl/dronet:5.16.20-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.17.15",kernel: "docker.io/aldokcl/dronet:5.17.15-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.18.19",kernel: "docker.io/aldokcl/dronet:5.18.19-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "5.19.17",kernel: "docker.io/aldokcl/dronet:5.19.17-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "6.0.6",kernel: "docker.io/aldokcl/dronet:6.0.6-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "6.1.0",kernel: "docker.io/aldokcl/dronet:6.1-amd64", image: "{{ defaultBaseImage }}"}
  - {name: "6.2.0",kernel: "docker.io/aldokcl/dronet:6.2-amd64", image: "{{ defaultBaseImage }}"}
```

The following issuer describes in detail the `testing-framework`:` falcosecurity/libs#1191

**Comment by incertum** [comment]
+1 :heart:

**Comment by jasondellaluce** [comment]
+1

**Comment by leogr** [comment]
big +1 :star_struck:

**Comment by maxgio92** [comment]
+1 lovely

**Comment by LucaGuerra** [comment]
This is FANTASTIC :star_struck: +1

**Comment by leogr** [comment]
PS
I volunteer to be a maintainer of this repo, if you need any help

**Comment by Andreagit97** [comment]
+1 :heart_eyes:

**Comment by FedeDP** [comment]
The repo has been successfully donated.
We can close this one.
