### ISSUE TITLE
Donating rohith-raju/Flaco-playground (GSoC 2023 project) to falco organization

### ISSUE THREAD

**Issue by Rohith-Raju** [falcosecurity/evolution#303]
### Project
Repo: https://github.com/rohith-raju/falco-playground
Playground: https://rohith-raju.github.io/falco-playground/

I had the pleasure of working on a project for Google Summer of Code (GSoC) with my mentor, @jasondellaluce. It was a fantastic experience from start to finish, and I'm grateful to all the members who made this my best summer yet. Together, we've decided to donate our project, which we've named `falcosecurity/playground`, to the Falcosecurity organization. We plan to continue improving it, with @jasondellaluce, @leogr, and myself taking on the responsibility of maintaining `falco-playground`. If any Falco maintainers would like to volunteer as a maintainer for `falco-playground`, we would greatly appreciate it!
 
### Motivation

The idea for this project is to add WebAssembly as a new officially-supported compilation target for Falco by leveraging the [Emscripten toolchain](https://emscripten.org/), and creating a new development environment for security rules in the form of a web single-page application by running Falco right inside the browser. The end result is envisioned to be similar to [the Go Playground](https://go.dev/play/), but without the need of any backend.

### Current state 
I am happy to report that the project has been successfully constructed using `React` and is functioning exceptionally well. As per the guidelines of the GSoC program, it is mandatory for the students to submit a functional MVP/prototype by the end of the program. If you are interested in knowing more about the proposal, you can refer to #262. For more info about the submission please click on the following link: https://developers.google.com/open-source/gsoc/help/work-product.

### Updates / Improvements
During a recent Falco community meeting, I shared a demo and received many helpful suggestions. One such suggestion was to **validate the rule file with multiple Falco versions**. This feature will be supported by upcoming Falco versions, as Falco can now be compiled to wasm. We have also taken into account suggestions for code refactoring and adding more test cases. Additionally, we welcome any feature requests or bug reports from the community.

**Comment by leogr** [comment]
Ofc, big +1 from me :star_struck:

**Comment by maxgio92** [comment]
Amazing @Rohith-Raju and @jasondellaluce!

+1

**Comment by FedeDP** [comment]
Big big +1 from me!

**Comment by zuc** [comment]
Amazing! +1 from me

**Comment by Andreagit97** [comment]
amazing work! +1

**Comment by mikegcoleman** [comment]
This is super cool. Congrats!

**Comment by leogr** [comment]
This is done!
/close
