### ISSUE TITLE
Donate fededp/dbg-go to falcosecurity

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/evolution#316]
**Repository**:  

https://github.com/FedeDP/dbg-go

**Motivation**

`dbg-go` is a swiss army knife tool to work with test-infra [drivers build grid](https://github.com/falcosecurity/test-infra/tree/master/driverkit).
It will allow us to completely drop driverkit folder Makefile and scripts (i already opened such a PR: https://github.com/falcosecurity/test-infra/pull/1204 that needs to fixup the `fededp` github user once it gets donated) replacing it with a well tested, maintained go tool.

Moreover, the go tool is also much quicker; from my benchmarks, configs generation with current bash scripts takes ~40min on my laptop for a single driver version. The dbg-go tool has a [benchmark](https://github.com/FedeDP/dbg-go/blob/main/pkg/generate/generate_test.go#L12) that takes ~1s to run, meaning that generating configs now takes 1s. 

Also, the `build` command is now capable of publishing drivers while building, in an async manner. 
This spots 2 big benefits:
* drivers will become available right after being built (without waiting all drivers to be built before starting the publish)
* time spent uploading drivers is saved, since it is done async

Finally, note that driverkit is now used as a library from within `dbg-go`; this should also speed up drivers build a bit because we avoid the overhead of spawning a new process for each driverkit config to be built, spawning a single process (dbg-go) that builds everything.

`dbg-go` supports same filters as old Makefile's scripts (per-target, per-kernelrelease and per-kernelversion); to glance at how it works inside test-infra, please refer to https://github.com/falcosecurity/test-infra/pull/1204

**Comment by leogr** [comment]
:heart_eyes: 
+1 from me

count me in if you need help maintaining the project

**Comment by maxgio92** [comment]
Terrific @FedeDP <3 Count me in too :)

+1

**Comment by jasondellaluce** [comment]
Delightful as always! +1 from me.

**Comment by leogr** [comment]
Hey @FedeDP 

I believe nobody disagrees, so let's transfer the repo! :partying_face:
