### ISSUE TITLE
Donate alacuku/k8s-metacollector to falcosecurity

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/evolution#335]
**Repository**:  https://github.com/alacuku/k8s-metacollector

**Motivation**
Falco has a built-in functionality called **Kubernetes Metadata Enrichment**. It provides k8s metadata, fetched from the k8s **api-server**, used by Falco to enrich the **system-call events**. Furthermore, these metadata are available to users as **[events fields](https://falco.org/docs/reference/rules/supported-fields/#field-class-k8s)** to be used in the `conditions` and 'outputs' of Falco rules.

The current k8s client has a number of issues described in this issue falcosecurity/libs#987. 

The new component addresses those issues and scales in large environments with thousands of nodes. It is a standalone component deployed alongside Falco in a Kubernetes cluster. It connects to the Kubernetes API server and dispatches the metadata to the Falco instances.  For more info on the implementation details please refer to:
* falcosecurity/libs#987
*  https://github.com/alacuku/k8s-metacollector

Please note that, the repository is still a work in progress since we are working on a new Falco `plugin` that will be paired with the `metacollector` and provide Falco with the k8s metadata.

**Comment by Andreagit97** [comment]
Thank you for the amazing job! :rocket:  +1 from me :+1: 

count me in if you need help maintaining the project!

**Comment by leogr** [comment]
Big +1 from me! :partying_face:

**Comment by LucaGuerra** [comment]
+1 :tada: :rocket:

**Comment by FedeDP** [comment]
Big +1 from me!! :rocket:

**Comment by leogr** [comment]
PS count me as maintainer if you need help

**Comment by zuc** [comment]
+1 from me as well!

**Comment by jasondellaluce** [comment]
+1 for this!

**Comment by Issif** [comment]
Do you think we could extend this to more than just Kubernetes? I mean, collecting metadata for EC2, etc?

Huge +1 anyway :wink:

**Comment by leogr** [comment]
I guess we can proceed :) 

@alacuku I will help with the process.
/assign

Anyone other than @Andreagit97 and me is willing to maintain this project? :thinking: If so, please ping us. Thank you.

**Comment by Issif** [comment]
Count on me if others agree, I know go and k8s api.

**Comment by alacuku** [comment]
> Do you think we could extend this to more than just Kubernetes? I mean, collecting metadata for EC2, etc?

It could be extended for other use-cases, but currently, we are focused on replacing the old k8s metadata fetcher in Falco.

**Comment by leogr** [comment]
I guess this is done :partying_face: https://github.com/alacuku/k8s-metacollector
