### ISSUE TITLE
Create new repo `cncf-green-review-testing` for CNCF TAG Environmental Sustainability - Green Reviews WG Testing Integration

### ISSUE THREAD

**Issue by incertum** [falcosecurity/evolution#345]
**Motivation**

Create a dedicated repository at https://github.com/falcosecurity/cncf-green-review-testing. This repository will serve as the hosting platform for the Falco daemonset configurations for CNCF TAG Environmental Sustainability CNCF Green Reviews WG testing integration, which will be utilized in the following repository https://github.com/cncf-tags/green-reviews-tooling/tree/main, leveraging the Flux framework. The daemonset templates will resemble existing templates https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes, but they will be customized to serve the specific purpose. This customization will include specifying concrete namespace names and labels, as well as implementing the desired spec.nodeSelector and spec.affinity configurations tailored for the Green Reviews WG effort.

The initial directory structure could resemble the following, subject to evolution over time:

```
├── kustomize
│   ├── driver-bpf
│   ├── driver-kmod
│   ├── driver-modern-bpf
│   │   ├── configmap.yaml
│   │   ├── ...
│   │   └── daemonset.yaml
│   ├── kustomization.yaml
│   └── templates
│       ├── ...
│       └── serviceaccount.yaml
├── LICENSE
└── README.md
```

Since https://github.com/cncf-tags/green-reviews-tooling/tree/main would utilize a Flux watch, there might not be a need for CI. Nevertheless, we still need to investigate how to utilize/consume the metrics results.

In addition to hosting the Falco deployment, this repository may also accommodate microservices test applications or stress test applications. Their purpose would be to simulate realistic workloads within the CNCF testbed, enabling us to derive meaningful performance metrics.

References:

- https://github.com/falcosecurity/falco/issues/2435
- https://github.com/cncf/tag-env-sustainability/issues/183#issuecomment-1844814323
- https://fluxcd.io/flux/
- https://github.com/cncf-tags/green-reviews-tooling/tree/main
- https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes

**Comment by Andreagit97** [comment]
+1

**Comment by nikimanoledaki** [comment]
Thank you @incertum! This repository would help the WG Green Reviews deploy Falco on our infrastructure. Since we aim to support more CNCF Projects in the future, it would help tremendously if we could delegate the maintenance of project-specific configuration to the project maintainers.

To summarise our discussion, for isolation between CNCF Projects, we can start with the following basic namespace/node isolation:
- Contain everything in a namespace `falco` 
- Add a `spec.nodeSelector` such as `"cncf-project": "falco"` to each daemonset

**Comment by zuc** [comment]
+1!

**Comment by FedeDP** [comment]
+1 from my side!

**Comment by LucaGuerra** [comment]
+1

**Comment by maxgio92** [comment]
+1

**Comment by cpanato** [comment]
+1

**Comment by leogr** [comment]
Awesome, we can move forward with this. Is anyone willing to be included in this repo's `OWNERS` file? :thinking:

**Comment by maxgio92** [comment]
You can count me in @leogr ✋

**Comment by LucaGuerra** [comment]
I can also help with reviews

**Comment by leogr** [comment]
Great!

So, I'm starting to prepare the repo in the org. I'll keep you posted.
