### ISSUE TITLE
Falco Daemonset of Kind under Ubuntu/CentOS/WSL2 - Same issue

### ISSUE THREAD

**Issue by robotica72** [falcosecurity/evolution#4]
**Describe the bug**

I know its been mentioned in a few issues but I havent seen any resolution or a lot of discussion - so I was hoping to ask this one again - Trying to deploy a Falco DS on a Kind Cluster - I have tried it on Kind under Ubuntu 16.04 and 18.04, CentOS 8, and WSL2 (I expected WSL2 issues).   All have the same issue.

I have added the kernel-headers-$(uname -r) successfully - but still no luck.

**How to reproduce it**

Base Ubuntu installed - Standard Docker-ce and a two node Kind cluster.   Then deploy the Falco DS manifests. 

**Expected behaviour**

A functioning Falco POD(s)

**Screenshots**

* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco

Creating symlink /var/lib/dkms/falco/0.19.0/source ->
                 /usr/src/falco-0.19.0

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.4.0-142-generic cannot be found at
/lib/modules/4.4.0-142-generic/build or /lib/modules/4.4.0-142-generic/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.19.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.4.0-142-generic
Cannot find kernel config
Thu Feb 13 01:12:53 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Feb 13 01:12:53 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Feb 13 01:12:53 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Feb 13 01:12:53 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Thu Feb 13 01:12:53 2020: Unable to load the driver. Exiting.
Thu Feb 13 01:12:53 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

**Environment**

- Falco version:
0.19
- System info:
Standard Falco DS
- Cloud provider or hardware configuration:
- OS:
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel:
Linux kind 4.4.0-142-generic falcosecurity/falco#168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
K8s

**Additional context**

Tried the same deployment on Kind on multiple Kernels and Linux Distros - same type of issue on all of them. 

Hoping to create a lab for work and Falco is an important piece of the lab... Any ideas?

**Comment by maxgio92** [comment]
Hi @ssurovich  @Chwetion, thanks for sharing, did you solve this issue?
Did you happen to try with 0.22.1?

**Comment by robotica72** [comment]
Hi @maxgio92 - I did have it working on 0.22.1 - Apologies for the delayed reply.  I just changed over my installation this week to use the driverkit module creation, which is a little easier that this method :)  So kudos on the driverkit project, works very well.

**Comment by ssurovich** [comment]
Hi @maxgio92 - I did have it working on 0.22.1 - Apologies for the delayed reply. I just changed over my installation this week to use the driverkit module creation, which is a little easier that this method :) So kudos on the driverkit project, works very well.
