### ISSUE TITLE
Donate Falco plugin Rust SDK [Incubation level]

### ISSUE THREAD

**Issue by gnosek** [falcosecurity/evolution#405]
**Repository**: https://github.com/gnosek/falco-plugin-rs

Documentation: https://gnosek.github.io/falco-plugin-rs/falco_plugin/index.html

**Motivation**

Falco is a powerful runtime security tool with extensive integrations via plugins. To enhance this ecosystem, I developed the [Falco Plugin Rust SDK](https://github.com/gnosek/falco-plugin-rs), allowing developers to write Falco plugins in Rust. Rust ensures safety, performance, and efficiency, making it ideal for developing high-quality plugins. This project opens up the ecosystem to Rust developers, further extending Falco's reach.

So, I propose donating it to the Falcosecurity organization to benefit from increased visibility, better maintenance, and community contributions. I believe this donation will foster greater growth and usage within the Falco community.

**Comment by gnosek** [comment]
Welcome aboard @mrgian! :D

**Comment by leogr** [comment]
big plus one for me :star_struck:

**Comment by gnosek** [comment]
The more the merrier, welcome aboard @Andreagit97!

**Comment by LucaGuerra** [comment]
+1 of course 🚀

**Comment by leogr** [comment]
I guess it's time to prepare for the transfer :rocket: 

I'm on it
/assign

**Comment by leogr** [comment]
question for @gnosek 
Can we rename the repo to `plugin-sdk-rs` (to be consistent with our other [plugin SDKs](https://github.com/falcosecurity?q=plugin&type=all&language=&sort=))? :thinking:

**Comment by gnosek** [comment]
Sure, in the context of the falcosecurity org it's clear what the SDK is for without an explicit falco in the repo name :)

(the crates should still be named falco_* though IMO)

**Comment by FedeDP** [comment]
Big +1, amazing job!!!
