### ISSUE TITLE
Create kilt repository

### ISSUE THREAD

**Issue by admiral0** [falcosecurity/evolution#41]
**Description of Request**

Please open a repository called kilt to contain the project described by proposal https://github.com/falcosecurity/falco/pull/1388 and implemented in PR #40. This has already been discussed in the community call.

**Motivation**

For motivation see proposal in falco repository - PR https://github.com/falcosecurity/falco/pull/1388

**Comment by leogr** [comment]
For reference, yesterday's community call's meeting notes are :point_right: [here](https://github.com/falcosecurity/community/blob/871a3cad1dbdb99037489092c53bd83913a174bf/meeting-notes/2020-10-07.md#agenda). 

Nobody disagreed on creating the repository; thus, we can proceed now :partying_face:   

I'm also going to close https://github.com/falcosecurity/evolution/pull/40 in favor of this.

/assign @leodido 
/assign @fntlnz

**Comment by leodido** [comment]
Hey please take a look at https://github.com/falcosecurity/kilt  🎉  🍰
