### ISSUE TITLE
Donate falco-action [Sandbox level]

### ISSUE THREAD

**Issue by darryk10** [falcosecurity/evolution#412]
Repository: https://github.com/darryk10/falco-action

Documentation: https://github.com/darryk10/falco-action/blob/main/README.md

Motivation
Deep visibility into CI/CD pipelines is essential for ensuring that code released into production is secure and reliable. With this in mind, @loresuo and I have developed falco-action, a simple way to integrate Falco into CI/CD workflows. Leveraging Falco's powerful visibility into Linux kernel system calls, falco-action can be easily embedded into GitHub Actions to monitor the runtime behavior of CI/CD servers. By capturing critical runtime events, such as suspicious connections and file accesses, falco-action provides valuable insights that help detect anomalous activities in continuous integration environments, making it a valuable tool for safeguarding the CI/CD pipeline.

So, @loresuso and I propose donating it to the Falcosecurity organization to benefit from increased visibility, better maintenance, and community contributions. I believe this donation will foster greater growth and usage within the Falco community. 

@loresuso and I propose to serve as repository maintainers, but we gladly welcome additional maintainers and approvers!

**Comment by loresuso** [comment]
Totally supporting the project of course!

P.S. The README will change its face soon! @FedeDP

**Comment by leogr** [comment]
big +1 from me!

Also, I would like to volunteer as a maintainer, if it works for you!

**Comment by leogr** [comment]
cc @falcosecurity/core-maintainers

**Comment by cpanato** [comment]
Nice

+1

**Comment by cpanato** [comment]
I also volunteer to maintain it

**Comment by Issif** [comment]
+1 I like the idea

**Comment by LucaGuerra** [comment]
I had a chance to talk about this with @loresuso . +1 from me 🚀

**Comment by leogr** [comment]
Great! Since we have received only positive feedback, it's time to proceed :rocket: 
@darryk10 I'll prepare the setup, then ping you for the transfer.
/assign
