### ISSUE TITLE
List what is sandbox, incubating, official support

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/evolution#44]
**What to document**

We need a place to use as a truth where we list what is the status of the various projects/subprojects.

For example:

- falcosecurity/falco: official support
- falcosecurity/kilt: incubating
- and so on

In some cases, some features or release artifacts of certain projects might not have the same level of the project itself. For example ECR images for Falco are not official support yet.

**Comment by maxgio92** [comment]
/remove-lifecycle stale
I think #88 is a WIP, right @leogr?
/assign @leogr

**Comment by leogr** [comment]
#88 is ready for me!
