### ISSUE TITLE
Move VSCode plugin to falcosecurity

### ISSUE THREAD

**Issue by seishinsha** [falcosecurity/evolution#46]
**Description of Request**

Handoff of the VSCode plugin to falcosecurity.

**Motivation**

It might be in the best interest of the oss team to group all things falco related together.

**Comment by nestorsalceda** [comment]
We forget to add a reference for the current repo!

https://github.com/sysdiglabs/vscode-falco

**Comment by leodido** [comment]
> **Motivation**
> 
> It might be in the best interest of the oss team to group all things falco related together.

Agree 💯

**Comment by leodido** [comment]
One question.

Would you two commit as maintainers of the project? If yes, I'll put you two in the OWNERS file.

**Comment by leogr** [comment]
Agree too :partying_face:

**Comment by nestorsalceda** [comment]
I don't have time to do a proper job as a maintainer so I prefer to step down on this :(

**Comment by seishinsha** [comment]
> One question.
> 
> Would you two commit as maintainers of the project? If yes, I'll put you two in the OWNERS file.

Agree to maintain it, time allowing ;).

**Comment by leogr** [comment]
Any news?

**Comment by seishinsha** [comment]
Let's rock!
