### ISSUE TITLE
Falcosidekick UI

### ISSUE THREAD

**Issue by Issif** [falcosecurity/evolution#47]
**Description of Request**

I started few days ago a new project, a sidekick for `falcosidekick` 😄.

https://github.com/Issif/falcosidekick-ui

The idea is to get a simple Web UI which displays in real-time the latest events from `Falco`.

![image](https://user-images.githubusercontent.com/4520100/107286198-8d99be80-6a60-11eb-8fc3-017d21cd4dc8.png)

**Motivation**

I would like to incubate it and soon release it as an official project. I'll maintain it and @fjogeleit agrees to to do so with me (thanks to him).

The first step would be to migrate my own repo https://github.com/Issif/falcosidekick-ui into main `falcosecurity` organization

cc @leogr

**Comment by leogr** [comment]
This is great! So OK for me :+1: 

I also confirm my willingness to be in the [OWNERS](https://github.com/Issif/falcosidekick-ui/blob/master/OWNERS) file of this project.

PS 
Welcome to @fjogeleit :)

**Comment by fntlnz** [comment]
+1 for me

**Comment by leodido** [comment]
💯  +1

@fjogeleit feel free to ping me over slack to coordinate for the invite in the org.

Steps after that:
- Move the repository
- Create an OWNER file
- Setup Prow (@poiana) workflow
   - How do you guys will release?
   - How will you generate the CHANGELOG?

**Comment by leogr** [comment]
Btw, there's already an [OWNERS](https://github.com/Issif/falcosidekick-ui/blob/master/OWNERS) file, and it seems good to me.
I believe @cpanato agreed already to be in. Do you confirm?

**Comment by cpanato** [comment]
I confirm! but you all have more powers than me :)

**Comment by leodido** [comment]
Even better @leogr :)

@fjogeleit is in!

**Comment by Issif** [comment]
> Even better @leogr :)
> 
> @fjogeleit is in!

Yep, I prepared it 😉 

For release process I need to discuss with everybody, I'm waiting for go 1.16 with file embedding, it will be really usefull to share a single all-in binary with html inside.

**Comment by leogr** [comment]
Done!!! :partying_face: 
https://github.com/falcosecurity/falcosidekick-ui
