### ISSUE TITLE
kubernetes-response-engine

### ISSUE THREAD

**Issue by leodido** [falcosecurity/evolution#48]
I want to bring up some issues about the project https://github.com/falcosecurity/kubernetes-response-engine after discussing this in private with @leogr 

1. It seems unmaintained since April 2019.
2. It doesn't have OWNERS file
3. It doesn't have @poiana handling it
4. GitHub bot continues to open PR to fix security vulns in its dependencies
5. It still mentions Falco as "Sysdig Falco"

If the community thinks it's still useful and valuable we need maintainers to step-up and commit to maintain it.

Otherwise, we may need to archive it.

**Comment by leogr** [comment]
My vote goes for archiving the project (unless @nestorsalceda and/or @tembleking are willing to fix all the above issues soon?).

Btw, there now should be other ways to implement a response engine with Falco? cc @Issif @danpopSD

**Comment by Issif** [comment]
I agree, we developped last outputs of `falcosidekick` with that spirit.

**Comment by danpopSD** [comment]
with this and future updates to sidekick etc.   this repo should be archived (IMHO)

**Comment by nibalizer** [comment]
:+1:

**Comment by leogr** [comment]
Archived!
