### ISSUE TITLE
initcontainer in the k8s examples should be updated

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#5]
Since the `falcosecurity/probeloader` image is not supported anymore, we need to update the way the initcontainer works [here](https://github.com/falcosecurity/contrib/blob/64ee5144a35340c70320d2be88a6ab0e4045763c/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml#L22).
Now, the driver can be installed by using the `falco-driver-loader` script that's provided within official Falco's images.

Also, I believe that we don't need `falcoctl` in this process and the download URL is not needed anymore [here](https://github.com/falcosecurity/contrib/blob/64ee5144a35340c70320d2be88a6ab0e4045763c/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap-slim.yaml#L31) since https://github.com/falcosecurity/falco/pull/1158

**Additional context**

The new approach is going to be documented soon :point_right: https://github.com/falcosecurity/falco-website/issues/186

See @leodido comments:
- https://github.com/falcosecurity/contrib/pull/3#pullrequestreview-400796019
- https://github.com/falcosecurity/contrib/pull/3#discussion_r410744569

cc @maxgio92

**Comment by leogr** [comment]
A new approach for the initcontainer :point_right: https://github.com/falcosecurity/falco/issues/1171

**Comment by maxgio92** [comment]
@leogr  thanks, I’d wait then for the driverloader image implementation

**Comment by leogr** [comment]
See https://github.com/falcosecurity/evolution/issues/25
