### ISSUE TITLE
Bulk archiving of projects not up-to-date anymore

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#51]
List of unactive/unmaintained projects under the `falcosecurity` organization:

- https://github.com/falcosecurity/cloud-native-security-hub-backend
- https://github.com/falcosecurity/cloud-native-security-hub-frontend
- https://github.com/falcosecurity/cloud-native-security-hub
- https://github.com/falcosecurity/falco-google-kubernetes-marketplace
- https://github.com/falcosecurity/falco-kubernetes-workshop
- https://github.com/falcosecurity/katacoda-scenarios
- https://github.com/falcosecurity/falco-operator 

Moreover, the above projects:
-  are being updated anymore for more than 1 year (with the only exception of `falco-operator` which was updated for the last time on Jul 30, 2019)
-  do not define an `OWNERS` file (with the exception of the `cloud-native-security-hub-*` project)
- (most important) are not handled by @poiana (eg. no DCO enforcement).

For the above reasons, I propose to set those projects as *archived* (using the specific functionality of GitHub meant for this purpose). Ofc, exceptions from that list should be allowed if a project maintainer volunteers to revamp a project shortly.

**Comment by leogr** [comment]
Btw, the `falco-security-workshop` got another PR from the Dependant bot for a potential security issue, PTAL :point_down: 
https://github.com/falcosecurity/falco-security-workshop/pulls

**Comment by maxgio92** [comment]
Maybe the Falco Operator can be revived :(

**Comment by leodido** [comment]
/cc @falcosecurity/cloud-native-security-hub-maintainers 
/cc @falcosecurity/falco-operator-maintainers 


(some of these projects neither have a GitHub team assigned)

I vote to archive abandoned projects.

**Comment by leogr** [comment]
Done!
