### ISSUE TITLE
Revamping interactive learning resources (katacoda labs)

### ISSUE THREAD

**Issue by pabloopez** [falcosecurity/evolution#70]
The Falco community owns three **Katacoda labs** available in the [Katacoda portal](http://katacoda.com/falco). Currently, although available, they are unmaintained and some parts need some updating work. The [repository](https://github.com/falcosecurity/katacoda-scenarios) is currently archived.

For those in the community who might not know about this platform, it enables interactive training for any tool you can imagine. As long as the tool we want to feature in the lab can run in a Linux host, any interactive learning environment can be created. It provides lots of flexibility. It also has base images for Kubernetes (two node clusters).

This request involves the next **proposals**:
- ask to unarchive the repository
- taking ownership of the Katacoda repo and any maintenance and new course developments (this is not a requirement, but a proposal. I do not need to own the repository to make PRs and help building new content)
- fix the existing labs (I have already identified what needs to be done)
- identify and define with the community which new content might be created (I talked with @Issif about a new one featuring the new released Response Engine with falcosidekick)
- check if we can embed this labs in a new section in the falco-website
- any other educational you might identify as useful for the community. This is not a closed request and will surely benefit from other's feedback! Training is a great way to make tech more accessible and Katacoda provides newcomers a really easy and nice way to get started with a new tool. 

_For context: [this request](https://kubernetes.slack.com/archives/CMWH3EH32/p1619710439268400) was already brought up in the Falco community slack channel but I'd like to formalize this proposal through this Issue._

**Comment by Issif** [comment]
Hello, as discussed on Slack, this is a great idea (please add `falcosidekick` and `falcosidekick-ui` in rebuilding :wink:).

This is a topic we should discuss in community call, can you join us this afternoon? 

https://github.com/falcosecurity/community#falco-community-calls

Please, fill the agenda with your topic if you come, the link to hackmq file is https://hackmd.io/3qYPnZPUQLGKCzR14va_qg?edit

🙏

**Comment by pabloopez** [comment]
Thank you @Issif, it is done!

**Comment by leodido** [comment]
Pablo and future maintainers working [here](https://github.com/pabloopez/katacoda-scenarios)!

Thanks!

**Comment by pabloopez** [comment]
In the last community meeting, we talked about **embedding the labs in the blog**. This way we could give more visibility to this resources. And therefore, make them easier to access (but not too much, as any visit would load the environment and I think we should not be wasting resources!). 

Once all the changes are merged with the original repo (it has been forked, anyone who wants to make comments please ask here for access) we can start thinking about how/where we embed the labs. Right now @pomyslowynick (thank you!) is reviewing the proposed changes to the labs, so it should be ready soon.

In the meantime it would be great if someone with admin access to the blog (@leodido, maybe you?) could provide a placeholder to test this. I have a script we can test to see if the lab loads and works fine.

**Comment by developer-guy** [comment]
I want to help with this 🥳🙋🏻‍♂️
